module.exports = {
  RECEIVE_CREATE_ERROR: "RECEIVE_CREATE_ERROR",
  RECEIVE_LOGIN_SUCCESS: "RECEIVE_LOGIN_SUCCESS",
  RECEIVE_LOGIN_ERROR: "RECEIVE_LOGIN_ERROR",
  RECEIVE_LOGOUT_SUCCESS: "RECEIVE_LOGOUT_SUCCESS",
  RECEIVE_LOGOUT_ERROR: "RECEIVE_LOGOUT_ERROR"
};
