var FilterConstants = {
  UPDATE_BOUNDS: "UPDATE_BOUNDS",
  UPDATE_MIN_PRICE: "UPDATE_MIN_PRICE",
  UPDATE_MAX_PRICE: "UPDATE_MAX_PRICE",
  UPDATE_BEDROOMS: "UPDATE_BEDROOMS"

};

module.exports = FilterConstants;
