module.exports = {
  LISTINGS_RECEIVED: "LISTINGS_RECEIVED",
  SAVED_LISTINGS_RECEIVED: "SAVED_LISTINGS_RECEIVED",
  LISTING_SAVED: "LISTING_SAVED",
  SAVED_LISTING_DELETED: "SAVED_LISTING_DELETED"
};
